In [32]:
import pandas as pd
import scanpy as sc
import os
import numpy as np

In [33]:
import glob

In [34]:
barcodes_uro = pd.read_csv("~/resource/murine_blca/sample_barcodes.csv")

In [35]:
barcodes_uro

                  Barcode      Sample
0      AAACCCACACTACTTT-1  GSM5288668
1      AAACCCATCGGTCTGG-1  GSM5288668
2      AAACGAAAGAAGGATG-1  GSM5288668
3      AAACGAACACACACTA-1  GSM5288668
4      AAACGCTGTTAGGCTT-1  GSM5288668
...                   ...         ...
14790  TTTGATCGTACGAGCA-1  GSM5288674
14791  TTTGATCGTTGCTGAT-1  GSM5288674
14792  TTTGGAGCACCTTCCA-1  GSM5288674
14793  TTTGGAGCAGACAAAT-1  GSM5288674
14794  TTTGGTTGTACACGCC-1  GSM5288674

[14795 rows x 2 columns]

In [36]:
wkdir= "/Users/lidiayung/project/resource/perturbations/GSE174182_RAW"
os.chdir(wkdir)

In [8]:
barcodes_uro

In [174]:
sample="GSM5288669_Sample-4"

In [177]:
mtx

'GSM5288669_Sample-4_filtered_matrix.mtx.gz'

In [160]:
#Read documents into adata 

adata = sc.read_mtx(mtx)

In [37]:
#For raw data retrival 
def subset(data,name):
    mtx =f"{data}_filtered_matrix.mtx.gz"
    cells=pd.read_csv(f"{data}_filtered_barcodes.tsv.gz",header=None)
    features=pd.read_csv(f'{data}_filtered_features.tsv.gz',header=None,sep='\t')
    adata = sc.read_mtx(mtx)
    
    adata= adata.T
    print(adata)
    adata.obs['CellID']= cells[0].tolist()
    adata.var['Gene']= features[1].tolist()
    adata.var.index= adata.var['Gene']
    
    adata.var_names_make_unique()
    barcodes_subset = barcodes_uro.loc[barcodes_uro['Sample'] == name, 'Barcode']
    adata_subset = adata[adata.obs['CellID'].isin(barcodes_subset)]
    print(adata_subset)
    adata_subset = adata_subset[:, adata_subset.var_names.isin(gene_list)]
    sc.pp.normalize_total(adata_subset, target_sum=1e4)
    sc.pp.log1p(adata_subset,base=2)
    adata_subset_df=adata_subset.to_df()
    adata_subset_df.to_pickle(f"{name}_sub.pkl")

In [ ]:
#For raw data retrival with LINCs genes

m_h_convertion = pd.read_csv("~/resource/m_h_convertion.csv")
gene_list = m_h_convertion['Mouse_Genes'].tolist()

def subset(data,name):
    mtx =f"{data}_filtered_matrix.mtx.gz"
    cells=pd.read_csv(f"{data}_filtered_barcodes.tsv.gz",header=None)
    features=pd.read_csv(f'{data}_filtered_features.tsv.gz',header=None,sep='\t')
    adata = sc.read_mtx(mtx)
    
    adata= adata.T
    print(adata)
    adata.obs['CellID']= cells[0].tolist()
    adata.var['Gene']= features[1].tolist()
    adata.var.index= adata.var['Gene']
    
    adata.var_names_make_unique()
    barcodes_subset = barcodes_uro.loc[barcodes_uro['Sample'] == name, 'Barcode']
    adata_subset = adata[adata.obs['CellID'].isin(barcodes_subset)]
    adata_subset = adata_subset[:, adata_subset.var_names.isin(gene_list)]
    sc.pp.normalize_total(adata_subset, target_sum=1e4)
    sc.pp.log1p(adata_subset,base=2)
    adata_subset_df=adata_subset.to_df()
    print(adata_subset_df)
    adata_subset_df.to_pickle(f"~/raw_lincs/{name}_raw_sub.pkl")

In [ ]:
mtx =f"GSM5288669_Sample-4_filtered_matrix.mtx.gz"
cells=pd.read_csv(f"GSM5288669_Sample-4_filtered_barcodes.tsv.gz",header=None)
features=pd.read_csv(f'GSM5288669_Sample-4_filtered_features.tsv.gz',header=None,sep='\t')
adata = sc.read_mtx(mtx)

barcodes_subset = barcodes_uro.loc[barcodes_uro['Sample'] == "GSM5288669", 'Barcode']

In [38]:
subset("GSM5288670_Sample-5","GSM5288670")

AnnData object with n_obs × n_vars = 9570 × 31053
View of AnnData object with n_obs × n_vars = 2508 × 31053
    obs: 'CellID'
    var: 'Gene'

/Users/lidiayung/miniconda3/lib/python3.9/site-packages/scanpy/preprocessing/_normalization.py:169: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)

In [185]:
subset("GSM5288672_Sample-7","GSM5288672")

AnnData object with n_obs × n_vars = 2964 × 31053
View of AnnData object with n_obs × n_vars = 1115 × 31053
    obs: 'CellID'
    var: 'Gene'

/Users/lidiayung/miniconda3/lib/python3.9/site-packages/scanpy/preprocessing/_normalization.py:169: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)

In [187]:
subset("GSM5288673_Sample-8","GSM5288673")

AnnData object with n_obs × n_vars = 4581 × 31053
View of AnnData object with n_obs × n_vars = 1878 × 31053
    obs: 'CellID'
    var: 'Gene'

/Users/lidiayung/miniconda3/lib/python3.9/site-packages/scanpy/preprocessing/_normalization.py:169: UserWarning: Received a view of an AnnData. Making a copy.
  view_to_actual(adata)

In [ ]:
subset("GSM5288671_Sample-6","GSM5288671")

In [145]:
!pwd

/Users/lidiayung/project/resource/perturbations/GSE174182_RAW

In [5]:
GSM5288673_sub =pd.read_pickle("/Users/lidiayung/project/resource/perturbations/GSE174182_RAW/pkl/GSM5288673_sub.pkl")

In [7]:
GSM5288673_sub.index

Index(['4', '7', '10', '13', '14', '15', '16', '19', '27', '29',
       ...
       '4561', '4564', '4565', '4567', '4571', '4572', '4575', '4577', '4579',
       '4580'],
      dtype='object', length=1878)

In [11]:
GSM5288671_sub['cell_id'] = "GSM5288671_"+GSM5288671_sub.index
GSM5288671_sub.set_index("cell_id",inplace=True)
pd.to_pickle(GSM5288671_sub,"GSM5288671_sub.pkl")

In [15]:
GSM5288673_sub.reset_index(inplace=True)

In [16]:
GSM5288673_sub

Gene,index,Xkr4,Gm1992,Gm37381,Rp1,Sox17,Gm37323,Mrpl15,Lypla1,Gm37988,...,AC125149.2,AC125149.4,AC234645.1,AC168977.2,AC168977.1,AC149090.1,CAAA01118383.1,Vmn2r122,CAAA01147332.1,cell_id
0,4,0.0,0.0,0.0,0.0,0.0,0.0,1.235163,0.167484,0.0,...,0.0,0.0,0.0,0.0,0.167484,0.691972,0.317531,0.0,0.0,GSM5288673_4
1,7,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,GSM5288673_7
2,10,0.0,0.0,0.0,0.0,0.0,0.0,0.662117,0.368714,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.905816,0.662117,0.0,0.0,GSM5288673_10
3,13,0.0,0.0,0.0,0.0,0.0,0.0,1.404521,0.377966,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.201326,0.377966,0.0,0.0,GSM5288673_13
4,14,0.0,0.0,0.0,0.0,0.0,0.0,1.768664,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,1.049594,0.341971,0.0,0.0,GSM5288673_14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1873,4572,0.0,0.0,0.0,0.0,0.0,0.0,0.428803,0.428803,0.0,...,0.0,0.0,0.0,0.0,0.000000,1.449209,0.000000,0.0,0.0,GSM5288673_4572
1874,4575,0.0,0.0,0.0,0.0,0.0,0.0,1.729978,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,GSM5288673_4575
1875,4577,0.0,0.0,0.0,0.0,0.0,0.0,0.400549,0.400549,0.0,...,0.0,0.0,0.0,0.0,0.000000,1.378540,0.400549,0.0,0.0,GSM5288673_4577
1876,4579,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,GSM5288673_4579
1877,4580,0.0,0.0,0.0,0.0,0.0,0.0,0.900869,0.283089,0.0,...,0.0,0.0,0.0,0.0,0.283089,1.848626,0.000000,0.0,0.0,GSM5288673_4580

In [23]:
GSM5288674_sub['Cell_id']=GSM5288674_sub['cell_id'].str[11:]

0          4
1          7
2         10
3         13
4         14
        ...
1873    4572
1874    4575
1875    4577
1876    4579
1877    4580
Name: cell_id, Length: 1878, dtype: object

In [30]:
GSM5288673_sub

Gene,index,Xkr4,Gm1992,Gm37381,Rp1,Sox17,Gm37323,Mrpl15,Lypla1,Gm37988,...,AC125149.4,AC234645.1,AC168977.2,AC168977.1,AC149090.1,CAAA01118383.1,Vmn2r122,CAAA01147332.1,cell_id,Extracted_Part
0,4,0.0,0.0,0.0,0.0,0.0,0.0,1.235163,0.167484,0.0,...,0.0,0.0,0.0,0.167484,0.691972,0.317531,0.0,0.0,GSM5288673_4,4
1,7,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,GSM5288673_7,7
2,10,0.0,0.0,0.0,0.0,0.0,0.0,0.662117,0.368714,0.0,...,0.0,0.0,0.0,0.000000,0.905816,0.662117,0.0,0.0,GSM5288673_10,10
3,13,0.0,0.0,0.0,0.0,0.0,0.0,1.404521,0.377966,0.0,...,0.0,0.0,0.0,0.000000,0.201326,0.377966,0.0,0.0,GSM5288673_13,13
4,14,0.0,0.0,0.0,0.0,0.0,0.0,1.768664,0.000000,0.0,...,0.0,0.0,0.0,0.000000,1.049594,0.341971,0.0,0.0,GSM5288673_14,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1873,4572,0.0,0.0,0.0,0.0,0.0,0.0,0.428803,0.428803,0.0,...,0.0,0.0,0.0,0.000000,1.449209,0.000000,0.0,0.0,GSM5288673_4572,4572
1874,4575,0.0,0.0,0.0,0.0,0.0,0.0,1.729978,0.000000,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,GSM5288673_4575,4575
1875,4577,0.0,0.0,0.0,0.0,0.0,0.0,0.400549,0.400549,0.0,...,0.0,0.0,0.0,0.000000,1.378540,0.400549,0.0,0.0,GSM5288673_4577,4577
1876,4579,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,GSM5288673_4579,4579
1877,4580,0.0,0.0,0.0,0.0,0.0,0.0,0.900869,0.283089,0.0,...,0.0,0.0,0.0,0.283089,1.848626,0.000000,0.0,0.0,GSM5288673_4580,4580

In [29]:
GSM5288668_sub['cell_id']= "GSM5288673_"+GSM5288673_sub['cell_id']

In [22]:
GSM5288668_sub['Cell_id'] = GSM5288668_sub['cell_id'].str[22:]  # Assuming "Sample" has length 6

In [ ]:
# Assuming df is your pandas DataFrame with the "New_Column" already created

# Extract part of the string after a certain position

# Or extract part of the string using a specific delimiter
GSM5288673_sub['Extracted_Part'] = GSM5288673_sub['cell_id'].str.split('Sample').str[-1].str.strip()

# Now df contains the extracted part of the "New_Column" values in a new column named "Extracted_Part"

In [ ]:
import scipy.sparse as sp
import pandas as pd
import scanpy as sc
import os
import numpy as np

In [ ]:
#For lincs data
def subset(data):
    mtx =f"{data}_corrected_UMI.mtx"
    cells=pd.read_csv(f"{data}_corrected_UMI_cells.txt",header=None)
    features=pd.read_csv(f'{data}_corrected_UMI_genes.txt',header=None)
    adata = sc.read_mtx(mtx)
    
    adata.obs['CellID']= cells[0].tolist()
    adata.var['Gene']= features[0].tolist()
    adata.var.index= adata.var['Gene']
    adata.var_names_make_unique()
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata,base=2)
    adata_subset_df=adata.to_df()
    print(adata_subset_df)
    adata_subset_df.to_pickle(f"out_dir_pkl_full/{data}_sct_full_final.pkl")